/**
 * events.js — Chicago Civic Match calendar dataset
 * ------------------------------------------------
 * GENERATED FILE — do not hand-edit. Edit events.csv and re-run
 * `python3 convert.py` instead.
 *
 * off = days from "today" at page-load time (0 = today), so the demo
 * calendar never goes stale. orgId matches an id in ORGS (data.js) —
 * see EVENT_ORG_CODES in convert.py for the short-code mapping.
 */

const EVENTS = [
  {
    "id": 1,
    "orgId": 5,
    "t": "Community Kitchen Dinner Service",
    "d": "Plate and serve the nightly hot meal in Rogers Park.",
    "off": 0,
    "h": 16,
    "m": 30,
    "dur": 180,
    "loc": "7649 N Paulina St",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 2,
    "orgId": 1,
    "t": "Saturday Morning Repack Session",
    "d": "Sort and box produce for pantries across Cook County. Closed-toe shoes required.",
    "off": 1,
    "h": 9,
    "m": 0,
    "dur": 180,
    "loc": "4100 W Ann Lurie Pl",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 3,
    "orgId": 6,
    "t": "Weekend Rescue Blitz",
    "d": "Extra drivers needed for surplus pickups citywide.",
    "off": 1,
    "h": 10,
    "m": 0,
    "dur": 60,
    "loc": "Citywide, choose your route",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 4,
    "orgId": 28,
    "t": "Route Delivery Day",
    "d": "Deliver meals and a friendly check-in to homebound seniors.",
    "off": 1,
    "h": 10,
    "m": 30,
    "dur": 120,
    "loc": "Pickup: multiple sites",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 5,
    "orgId": 45,
    "t": "Voter Registration Pop-Up",
    "d": "Register new voters at the farmers market.",
    "off": 1,
    "h": 8,
    "m": 0,
    "dur": 240,
    "loc": "Wicker Park Farmers Market",
    "kind": "event",
    "signup": "https://example.org/signup"
  },
  {
    "id": 6,
    "orgId": 5,
    "t": "Sunday Dinner Service",
    "d": "Serve the evening meal, every single day of the year.",
    "off": 2,
    "h": 16,
    "m": 30,
    "dur": 180,
    "loc": "7649 N Paulina St",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 7,
    "orgId": 29,
    "t": "Dog Walking Orientation",
    "d": "Required intro before you can walk and socialize shelter dogs.",
    "off": 2,
    "h": 11,
    "m": 0,
    "dur": 90,
    "loc": "1997 N Clybourn Ave",
    "kind": "training",
    "signup": "https://example.org/signup"
  },
  {
    "id": 8,
    "orgId": 13,
    "t": "Know Your Rights Training",
    "d": "Get trained to lead rights workshops in your own community.",
    "off": 3,
    "h": 18,
    "m": 0,
    "dur": 120,
    "loc": "Online",
    "kind": "training",
    "signup": "https://example.org/signup"
  },
  {
    "id": 9,
    "orgId": 31,
    "t": "Cat Socializing Hour",
    "d": "Sit with shy cats and help them learn to trust people.",
    "off": 3,
    "h": 17,
    "m": 0,
    "dur": 60,
    "loc": "7225 N Western Ave",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 10,
    "orgId": 12,
    "t": "Welcome Team Orientation",
    "d": "Learn how apartment setups and airport welcomes work.",
    "off": 4,
    "h": 18,
    "m": 0,
    "dur": 90,
    "loc": "Online",
    "kind": "training",
    "signup": "https://example.org/signup"
  },
  {
    "id": 11,
    "orgId": 20,
    "t": "Shelter Homework Lab",
    "d": "Tutor kids in reading and math right inside the shelter.",
    "off": 4,
    "h": 16,
    "m": 0,
    "dur": 120,
    "loc": "Address shared on signup",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 12,
    "orgId": 45,
    "t": "Text Bank Tuesday",
    "d": "Send get-out-the-vote texts together on a video call.",
    "off": 4,
    "h": 18,
    "m": 30,
    "dur": 90,
    "loc": "Online",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 13,
    "orgId": 1,
    "t": "Weekday Evening Repack",
    "d": "After-work shift on the warehouse floor.",
    "off": 5,
    "h": 17,
    "m": 30,
    "dur": 150,
    "loc": "4100 W Ann Lurie Pl",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 14,
    "orgId": 19,
    "t": "Story Time Volunteer Session",
    "d": "Read with young students during a literacy session.",
    "off": 5,
    "h": 15,
    "m": 30,
    "dur": 90,
    "loc": "651 W Lake St",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 15,
    "orgId": 50,
    "t": "Morning Motivations",
    "d": "Join the daily community circle and give a short motivational talk.",
    "off": 5,
    "h": 8,
    "m": 30,
    "dur": 45,
    "loc": "237 S Desplaines St",
    "kind": "event",
    "signup": "https://example.org/signup"
  },
  {
    "id": 16,
    "orgId": 12,
    "t": "Apartment Setup Day",
    "d": "Furnish a home before a newly arriving family lands next week.",
    "off": 6,
    "h": 10,
    "m": 0,
    "dur": 180,
    "loc": "Uptown, address on signup",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 17,
    "orgId": 26,
    "t": "Friendly Caller Training",
    "d": "Learn the ropes of weekly check-in calls with isolated elders.",
    "off": 6,
    "h": 12,
    "m": 0,
    "dur": 60,
    "loc": "Online",
    "kind": "training",
    "signup": "https://example.org/signup"
  },
  {
    "id": 18,
    "orgId": 7,
    "t": "Hygiene Kit Build Night",
    "d": "Assemble kits with soap, socks, and essentials for street outreach.",
    "off": 6,
    "h": 18,
    "m": 0,
    "dur": 120,
    "loc": "1735 N Ashland Ave",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 19,
    "orgId": 18,
    "t": "Teen Showcase Judging Night",
    "d": "Score final projects as teens present their apprenticeship work.",
    "off": 7,
    "h": 17,
    "m": 0,
    "dur": 150,
    "loc": "66 E Randolph St",
    "kind": "event",
    "signup": "https://example.org/signup"
  },
  {
    "id": 20,
    "orgId": 8,
    "t": "Housing Advocacy Phone Bank",
    "d": "Call supporters ahead of the city budget hearing.",
    "off": 7,
    "h": 17,
    "m": 30,
    "dur": 120,
    "loc": "Online",
    "kind": "advocacy",
    "signup": "https://example.org/signup"
  },
  {
    "id": 21,
    "orgId": 29,
    "t": "Adoption Event: Fees Waived Weekend",
    "d": "Help staff the busiest adoption weekend of the summer.",
    "off": 8,
    "h": 10,
    "m": 0,
    "dur": 360,
    "loc": "1997 N Clybourn Ave",
    "kind": "event",
    "signup": "https://example.org/signup"
  },
  {
    "id": 22,
    "orgId": 32,
    "t": "Riverbank Cleanup: North Branch",
    "d": "Pull trash and invasive plants. Gloves and tools provided.",
    "off": 8,
    "h": 9,
    "m": 0,
    "dur": 180,
    "loc": "River Park, 5100 N Francisco Ave",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 23,
    "orgId": 13,
    "t": "Citizenship Workshop Volunteer Day",
    "d": "Help staff a naturalization workshop. Non-attorneys needed too.",
    "off": 8,
    "h": 9,
    "m": 0,
    "dur": 300,
    "loc": "224 S Michigan Ave",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 24,
    "orgId": 50,
    "t": "Mock Interview Day",
    "d": "Coach job seekers through practice interviews.",
    "off": 9,
    "h": 13,
    "m": 0,
    "dur": 180,
    "loc": "237 S Desplaines St",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 25,
    "orgId": 48,
    "t": "Expungement Clinic",
    "d": "Walk clients through record-clearing paperwork. Training on site.",
    "off": 10,
    "h": 9,
    "m": 0,
    "dur": 240,
    "loc": "Legal Aid office, Loop",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 26,
    "orgId": 14,
    "t": "After-School Tutoring Kickoff",
    "d": "New tutor orientation for the fall term in West Town.",
    "off": 11,
    "h": 17,
    "m": 30,
    "dur": 90,
    "loc": "1347 W Erie St",
    "kind": "training",
    "signup": "https://example.org/signup"
  },
  {
    "id": 27,
    "orgId": 8,
    "t": "City Budget Hearing: Show Up",
    "d": "Pack the room when housing funding is on the docket.",
    "off": 12,
    "h": 10,
    "m": 0,
    "dur": 180,
    "loc": "City Hall, 121 N LaSalle St",
    "kind": "advocacy",
    "signup": "https://example.org/signup"
  },
  {
    "id": 28,
    "orgId": 32,
    "t": "Paddle & Patrol",
    "d": "Canoe cleanup crew on the main stem. Paddling experience helpful.",
    "off": 13,
    "h": 9,
    "m": 30,
    "dur": 180,
    "loc": "Clark Park Boathouse",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 29,
    "orgId": 5,
    "t": "Community Kitchen Dinner Service",
    "d": "Plate and serve the nightly hot meal in Rogers Park.",
    "off": 14,
    "h": 16,
    "m": 30,
    "dur": 180,
    "loc": "7649 N Paulina St",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 30,
    "orgId": 1,
    "t": "Saturday Morning Repack Session",
    "d": "Sort and box produce for pantries across Cook County.",
    "off": 15,
    "h": 9,
    "m": 0,
    "dur": 180,
    "loc": "4100 W Ann Lurie Pl",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 31,
    "orgId": 29,
    "t": "Dog Walking Orientation",
    "d": "Required intro before you can walk and socialize shelter dogs.",
    "off": 16,
    "h": 11,
    "m": 0,
    "dur": 90,
    "loc": "1997 N Clybourn Ave",
    "kind": "training",
    "signup": "https://example.org/signup"
  },
  {
    "id": 32,
    "orgId": 45,
    "t": "Text Bank Tuesday",
    "d": "Send get-out-the-vote texts together on a video call.",
    "off": 18,
    "h": 18,
    "m": 30,
    "dur": 90,
    "loc": "Online",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 33,
    "orgId": 20,
    "t": "Shelter Homework Lab",
    "d": "Tutor kids in reading and math right inside the shelter.",
    "off": 18,
    "h": 16,
    "m": 0,
    "dur": 120,
    "loc": "Address shared on signup",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 34,
    "orgId": 13,
    "t": "Rights Workshop: Train the Trainer",
    "d": "Second session in the know-your-rights series.",
    "off": 19,
    "h": 18,
    "m": 0,
    "dur": 120,
    "loc": "Online",
    "kind": "training",
    "signup": "https://example.org/signup"
  },
  {
    "id": 35,
    "orgId": 7,
    "t": "Outreach Bus Ride-Along",
    "d": "Join the evening health outreach team and see the work up close.",
    "off": 20,
    "h": 19,
    "m": 0,
    "dur": 180,
    "loc": "Departs 1735 N Ashland Ave",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 36,
    "orgId": 32,
    "t": "Riverbank Cleanup: South Branch",
    "d": "Gloves and tools provided. Families welcome.",
    "off": 22,
    "h": 9,
    "m": 0,
    "dur": 180,
    "loc": "Canal Origins Park",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 37,
    "orgId": 28,
    "t": "Route Delivery Day",
    "d": "Deliver meals and a friendly check-in to homebound seniors.",
    "off": 22,
    "h": 10,
    "m": 30,
    "dur": 120,
    "loc": "Pickup: multiple sites",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 38,
    "orgId": 8,
    "t": "Housing Town Hall",
    "d": "Hear directly from unhoused leaders and city officials. Bring questions.",
    "off": 23,
    "h": 18,
    "m": 0,
    "dur": 120,
    "loc": "Harold Washington Library",
    "kind": "advocacy",
    "signup": "https://example.org/signup"
  },
  {
    "id": 39,
    "orgId": 14,
    "t": "Citizenship Class Assist",
    "d": "Help adults prep for the naturalization test.",
    "off": 25,
    "h": 18,
    "m": 0,
    "dur": 90,
    "loc": "1347 W Erie St",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 40,
    "orgId": 31,
    "t": "Community Cats 101",
    "d": "Learn how the TNR program works and how to join a colony team.",
    "off": 26,
    "h": 17,
    "m": 30,
    "dur": 90,
    "loc": "7225 N Western Ave",
    "kind": "training",
    "signup": "https://example.org/signup"
  },
  {
    "id": 41,
    "orgId": 50,
    "t": "Morning Motivations",
    "d": "Join the daily community circle and give a short motivational talk.",
    "off": 27,
    "h": 8,
    "m": 30,
    "dur": 45,
    "loc": "237 S Desplaines St",
    "kind": "event",
    "signup": "https://example.org/signup"
  },
  {
    "id": 42,
    "orgId": 19,
    "t": "Fall Book Drive Sorting Day",
    "d": "Process the season's biggest donation haul.",
    "off": 29,
    "h": 10,
    "m": 0,
    "dur": 240,
    "loc": "651 W Lake St",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 43,
    "orgId": 12,
    "t": "World Refugee Community Dinner",
    "d": "Share a meal cooked by newly arrived families. Tickets support resettlement.",
    "off": 30,
    "h": 18,
    "m": 0,
    "dur": 150,
    "loc": "Uptown, address on signup",
    "kind": "event",
    "signup": "https://example.org/signup"
  },
  {
    "id": 44,
    "orgId": 1,
    "t": "Hunger Action Phone Bank",
    "d": "Call Cook County residents about SNAP renewal deadlines.",
    "off": 32,
    "h": 17,
    "m": 30,
    "dur": 120,
    "loc": "Online",
    "kind": "advocacy",
    "signup": "https://example.org/signup"
  },
  {
    "id": 45,
    "orgId": 18,
    "t": "Fall Program Mentor Kickoff",
    "d": "Meet your teen apprentice cohort for the fall term.",
    "off": 33,
    "h": 17,
    "m": 0,
    "dur": 120,
    "loc": "66 E Randolph St",
    "kind": "training",
    "signup": "https://example.org/signup"
  },
  {
    "id": 46,
    "orgId": 26,
    "t": "Birthday Brigade",
    "d": "Celebrate elders' birthdays with cake, cards, and company.",
    "off": 35,
    "h": 14,
    "m": 0,
    "dur": 120,
    "loc": "Bucktown, address on signup",
    "kind": "event",
    "signup": "https://example.org/signup"
  },
  {
    "id": 47,
    "orgId": 48,
    "t": "Expungement Clinic",
    "d": "Walk clients through record-clearing paperwork. Training on site.",
    "off": 36,
    "h": 9,
    "m": 0,
    "dur": 240,
    "loc": "Legal Aid office, Loop",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 48,
    "orgId": 29,
    "t": "Fall Adoption Fair",
    "d": "Help staff the big outdoor adoption event.",
    "off": 36,
    "h": 10,
    "m": 0,
    "dur": 300,
    "loc": "1997 N Clybourn Ave",
    "kind": "event",
    "signup": "https://example.org/signup"
  },
  {
    "id": 49,
    "orgId": 45,
    "t": "Voter Reg Deadline Push",
    "d": "Last-week registration sprint. Tables all over the city.",
    "off": 38,
    "h": 9,
    "m": 0,
    "dur": 360,
    "loc": "Citywide",
    "kind": "advocacy",
    "signup": "https://example.org/signup"
  },
  {
    "id": 50,
    "orgId": 6,
    "t": "Thanksgiving Surge Prep",
    "d": "Extra rescue routes as holiday demand climbs.",
    "off": 40,
    "h": 10,
    "m": 0,
    "dur": 60,
    "loc": "Citywide, choose your route",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  },
  {
    "id": 51,
    "orgId": 5,
    "t": "Community Kitchen Dinner Service",
    "d": "Plate and serve the nightly hot meal in Rogers Park.",
    "off": 41,
    "h": 16,
    "m": 30,
    "dur": 180,
    "loc": "7649 N Paulina St",
    "kind": "volunteer",
    "signup": "https://example.org/signup"
  }
];
